### ISSUE TITLE
encrypted message not appended

### ISSUE THREAD

**Issue by randogoth** [uakfdotb/gpg-mailgate#7]
hi. i installed gpg-mailgate on my running on Debian Wheezy vps and according to the logs, the script seems to kinda work - a bit ...

but unfortunately there is no encrypted message in my emails. they all arrive without message. the email source stops with the line:

"X-GPG-Mailgate: Encrypted by GPG Mailgate"

and then it's blank...

**Comment by uakfdotb** [comment]
This indicates that the call to gpg is not working properly. You should verify that the keyhome for gpg-mailgate has been set up properly (with read permission), and try running GnuPG.GPGEncryptor manually in Python, e.g.

```
import GnuPG
gpg = GnuPG.GPGEncryptor('/path/to/keyhome/', 'you@mail.com', 'UTF-8')
gpg.update("encryption test")
print gpg.encrypt()
```

**Comment by randogoth** [comment]
it's not working indeed...your script creates no result.

```
sudo -u gpgmap /usr/bin/gpg --list-keys --homedir=/var/gpg/.gnupg
```

correctly shows me the keyring with imported keys

**Comment by uakfdotb** [comment]
Why does this fail on your machine?

```
echo 'message' | sudo -u gpgmap /usr/bin/gpg --trust-model always --homedir /var/gpg/.gnupg --batch --yes --pgp7 --no-secmem-warning -a -e -r 'you@example.com'
```

Or, if it works, then that indicates that gpg-mailgate is not able to load /etc/gpg-mailgate.conf.

**Comment by randogoth** [comment]
that works!

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.12 (GNU/Linux)

hQEMA1KT6bwO2LQ8AQf+KAyi9COIp/ya0dxqYaL1y/VJsL/yVCMWKlDjwCXFINS6
JkpM7QDkwtZQnjNPknhlM9+e37eTe0rJziyYd/yqCAr/r3AsaIh7H3tr5iSZOGsq
bbf0ZhbOmc6ZzxmuzFJELlJsPZSTh1pou8VFYkkqB7JF5zgec00rZcfSJkWrPtoH
Dj5Y8bdhHzdUSL9JSDi9JLZ4Da2CmPrbndROttMQ7mZ3qBejl9DcAsxZ4/6HFxhA
eNUWanjHWC7XBhnxwMylWlaZ8hNn+ZymVZ2EmWvZsR1peLopSOmTpySGa32BUsPh
c8J3VruMY98iJr0iBdSlLKNLinkwENMHacX8YxFST9I9AaIm/osXlW10rJbgCfQW
omUJuEFfSGkzsrKbUrH/fTcVr2XdKZ3Qg6ndJ77OlOH7vwnoTHnimT23HsHojQ==
=0kBu
-----END PGP MESSAGE-----
```

gpg-mailgate also opens the .conf correctly. right now i am only using one address in the keymap section for testing and i only get the error for this one. the others have

```
X-GPG-Mailgate: Not encrypted, public key not found
```

in their header like they should

**Comment by uakfdotb** [comment]
The installation instructions are missing a step. You need to change this in master.cf:

```
gpg-mailgate    unix    -   n   n   -   -   pipe
        flags= user=nobody argv=/usr/local/bin/gpg-mailgate.py ${recipient}
```

to

```
gpg-mailgate    unix    -       n       n       -       -       pipe
        flags= user=gpgmap argv=/usr/local/bin/gpg-mailgate.py ${recipient}
```

**Comment by randogoth** [comment]
that was it! thanks a lot for the help!

**Comment by dejj** [comment]
I had the same problem. I had my [keymap] entries wrong in gpg-mailgate.conf.
wrong: myname@example.com = 1024D/AAAAAAAAAAAAAAAA
correct: myname@example.com = AAAAAAAAAAAAAAAA
