### ISSUE TITLE
new GnuPG python wrapper

### ISSUE THREAD

**Issue by randogoth** [uakfdotb/gpg-mailgate#8]
i just stumbled over this:

> > https://pythonhosted.org/python-gnupg/

how about using that instead of the gpg-mailgate GnuPG script...

i'd try to implement it myself, but i am a total python noob....(would be a good reason to get into it though, right? ;)

**Comment by uakfdotb** [comment]
Hm, one of the things needed for compatibility is to set the charset comment, I really am not sure what it means but it seems to be needed to prevent corruption of the text depending on how the email was encoded.
